<a href="https://colab.research.google.com/github/Rohit2303A510J0/python_for_data_science/blob/main/LAB-2/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy and Pandas

#Import Required Libraries

In [1]:
import numpy as np
import pandas as pd

#Create a NumPy Array

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print('Original Array:', arr)

Original Array: [10 20 30 40 50]


#Manipulate the NumPy Array

In [3]:
print(arr + 5) # Add 5 to each element
print(arr * 2) # Multiply each element by 2
print(arr[arr > 25]) # Filter elements > 25

[15 25 35 45 55]
[ 20  40  60  80 100]
[30 40 50]


#Create pandas DataFrame

In [4]:
# Create dictionary for the data
data = {
    'Name': ['Alice', 'Bob', 'Chalie', 'David'],
    'Age': [25, 30, 35, 40],
    'Score': [85.5, 92.0, 88.0, 76.5]
}

# Create DataFrame
df = pd.DataFrame(data)
print("\nOriginal DataFrame:\n", df)


Original DataFrame:
      Name  Age  Score
0   Alice   25   85.5
1     Bob   30   92.0
2  Chalie   35   88.0
3   David   40   76.5


#Manipulate the DataFrame